coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
        if_ci_failed: error
    patch:
      default:
        target: 90%
        threshold: 1%

comment:
  layout: "header, diff, flags, components"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "examples/"
  - "docs/"
  - "dist/"
  - "coverage/"
  - "*.config.js"
  - "*.config.ts"
  - "eslint.config.js"